name: angel_migration_runner
version: 2.0.0
description: Command-line based database migration runner for Angel's ORM.
author: Tobe O <thosakwe@gmail.com>
homepage: https://github.com/angel-dart/migration
environment:
  sdk: ">=2.0.0-dev <3.0.0"
dependencies:
  angel_migration: ^2.0.0-alpha
  angel_orm: ^2.0.0-dev.2
  args: ^1.0.0
  charcode: ^1.0.0
  postgres: ^2.1.1
  mysql1: ^0.17.1
dependency_overrides:
  angel_migration:
    path: "../angel_migration"
  angel_orm:
    path: "../angel_orm"
